name: Build and Copy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build
      run: python buildWeb.py
    - name: Upload outputs
      uses: actions/upload-artifact@v2
      with:
        name: outputs
        path: html/outputs.js
  scp:
    name: Copy
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: outputs
    - name: Copy artifact to dist dir
      run: cp outputs.js html/outputs.js
    - name: Copying
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CHOST }}
        username: ${{ secrets.CUSERNAME }}
        password: ${{ secrets.CPASSWORD }}
        source: html
        target: ${{ secrets.CPATH }}
        overwrite: true